//
//  ListMovieInterfaces.swift
//  MovieApp
//
//  Created by Christian Adiputra on 01/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

protocol ListMovieWireframeInterface: WireframeInterface {
    func goToDetailMovie(movieId: Int)
}

protocol ListMoviePresenterInterface: ViewInterface {
    func fetchDiscoverMovies()
    func fetchListGenre()
    func addPage()
    func setFilter(filter: [MovieGenre])
    func goToDetailMovie(movieId: Int)
    func getListDiscover() -> [Movie]
    func getListGenre() -> [MovieGenre]
    func getListSelectedGenre() -> [MovieGenre]
    func getRandomPoster() -> URL?
    func getTotalPages() -> Int
    var page: Int { get set }
}

protocol ListMovieOutputInteractorInterface: PresenterInterface {
    func didSuccessGetDiscover()
    func didSuccessGetGenres()
    func didFailedFetchData(message: String)
}

protocol ListMovieInteractorInterface: InteractorInterface {
    var totalPages: Int? { get set }
    var listDiscover: [Movie] { get set }
    var listGenre: [MovieGenre] { get set }
    var selectedGenre: [MovieGenre] { get set }
    func fetchListGenre()
    func fetchDiscoverMovies(page: Int)
}

protocol ListMovieViewInterface: ViewInterface {
    func updateList()
    func scrollToTop()
    func showAlert(message: String)
}
