//
//  ListMovieWireframe.swift
//  MovieApp
//
//  Created by Christian Adiputra on 01/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

final class ListMovieWireframe: BaseWireframe<ListMovieViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = ListMovieViewController()
        super.init(viewController: moduleViewController)

        let interactor = ListMovieInteractor()
        let presenter = ListMoviePresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension ListMovieWireframe: ListMovieWireframeInterface {
    func goToDetailMovie(movieId: Int) {
        navigationController?.pushWireframe(DetailMovieWireframe(movieId: movieId))
    }
    
}
