//
//  DetailMovieInterfaces.swift
//  MovieApp
//
//  Created by Christian Adiputra on 02/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit
import NetworkKit

protocol DetailMovieWireframeInterface: WireframeInterface {
}

protocol DetailMovieViewInterface: ViewInterface {
    func updateView()
    func updateTableView()
    func showAlert(message: String)
}

protocol DetailMoviePresenterInterface: PresenterInterface {
    func fetchDetailData()
    func addPage()
    func getImage() -> URL?
    func getMovieDetail() -> Movie?
    func getListReview() -> [MovieReview]
    func fetchListReview()
    func getTrailerURL() -> String?
    func getTotalPages() -> Int
    
    var movieId: Int? { get set }
    var page: Int { get set }
}

protocol DetailMovieInteractorInterface: InteractorInterface {
    func fetchDetailData(id: Int)
    func fetchListReview(page: Int, id: Int)
    var detailMovie: Movie? { get set }
    var listReview: [MovieReview] { get set }
    var totalPage: Int { get set }
}

protocol DetailMovieInteractorOutputInterface: InteractorOutputInterface {
    func successGetDetail()
    func successGetListReview()
    func didFailedFetchData(message: String)
}
