//
//  DetailMovieInteractor.swift
//  MovieApp
//
//  Created by Christian Adiputra on 02/07/23.
//  CopyrighOint (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import NetworkKit

final class DetailMovieInteractor {
    weak var presenter: DetailMovieInteractorOutputInterface?
    let movieService: MovieServiceProtocol = MovieService()
    
    var totalPage: Int = 2
    var detailMovie: Movie?
    var listReview: [MovieReview] = []
}

// MARK: - Extensions -

extension DetailMovieInteractor: DetailMovieInteractorInterface {
    
    func fetchListReview(page: Int, id: Int) {
        guard page <= totalPage else { return }
        movieService.getListReview(page: page, id: id) { response in
            guard let reviews = response.result else { return }
            self.listReview.append(contentsOf: reviews)
            self.presenter?.successGetListReview()
        } onFailure: { error in
            self.presenter?.didFailedFetchData(message: error.localizedDescription)
        }

    }
    
    func fetchDetailData(id: Int) {
        movieService.getDetailMovie(id: id) { response in
            self.detailMovie = response
            self.presenter?.successGetDetail()
        } onFailure: { error in
            self.presenter?.didFailedFetchData(message: error.localizedDescription)
        }

    }
    
    
}
