//
//  DetailMovieWireframe.swift
//  MovieApp
//
//  Created by Christian Adiputra on 02/07/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DesignKit

final class DetailMovieWireframe: BaseWireframe<DetailMovieViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init(movieId: Int) {
        let moduleViewController = DetailMovieViewController()
        super.init(viewController: moduleViewController)

        let interactor = DetailMovieInteractor()
        let presenter = DetailMoviePresenter(view: moduleViewController, interactor: interactor, wireframe: self, movieId: movieId)
        interactor.presenter = presenter
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailMovieWireframe: DetailMovieWireframeInterface {
}
